spring:
  datasource:
    url: jdbc:oracle:thin:@srv-dbora-07.whebdc.com.br:1521:Training_DB
    username: ${ORACLE_DB_USER}
    password: ${ORACLE_DB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      max-lifetime: 1800000
      connection-timeout: 30000
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.OracleDialect
        format_sql: true
        show_sql: true
        use_sql_comments: true
